workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "new_test"
      variables:
        DOCKERFILE_DIR: ./docker_api/
        PROJECT_NAME: matmaster-evo-new_test
        BRANCH: new_test
        COVER: "false"
    - if: $CI_COMMIT_BRANCH == "test"
      variables:
        DOCKERFILE_DIR: ./docker_api/
        PROJECT_NAME: matmaster-evo_test
        BRANCH: test
        COVER: "false"
    - if: $CI_COMMIT_TAG
      variables:
        DOCKERFILE_DIR: ./docker_api/
        COVER: "false"
