"""Verify builtin tools declare the expected self-describing metadata."""

from __future__ import annotations

import pytest

from matmaster.tools.builtin import (
    BashTool,
    EditTool,
    GlobTool,
    GrepTool,
    ListDirTool,
    ReadTool,
    SpawnTool,
    TaskCompleteTool,
    TaskCreateTool,
    TaskGetTool,
    TaskListTool,
    TaskUpdateTool,
    WebFetchTool,
    WebSearchTool,
    WriteTool,
)
from matmaster.tools.builtin.monitor_job import MonitorJobTool
from matmaster.types.tool_spec import ResourceClaim
from matmaster.types.topology import ToolPlane

BUILTIN_EXPECTATIONS = [
    (
        BashTool,
        (ResourceClaim(resource="session", mode="exclusive"),),
        frozenset({"shell.execute"}),
        "local_mutation",
        False,
        12000,
        ToolPlane.SESSION_SHELL,
        "stateless",
        "cancellable",
    ),
    (
        ListDirTool,
        (ResourceClaim(resource="session", mode="exclusive"),),
        frozenset({"workspace.list"}),
        "none",
        True,
        8000,
        ToolPlane.SESSION_SHELL,
        "stateless",
        "cancellable",
    ),
    (
        GlobTool,
        (ResourceClaim(resource="session", mode="exclusive"),),
        frozenset({"workspace.search.path"}),
        "none",
        True,
        8000,
        ToolPlane.SESSION_SHELL,
        "stateless",
        "cancellable",
    ),
    (
        GrepTool,
        (ResourceClaim(resource="session", mode="exclusive"),),
        frozenset({"workspace.search.content"}),
        "none",
        True,
        8000,
        ToolPlane.SESSION_SHELL,
        "stateless",
        "cancellable",
    ),
    (
        ReadTool,
        (ResourceClaim(resource="workspace", mode="shared_read"),),
        frozenset({"workspace.read"}),
        "none",
        True,
        12000,
        ToolPlane.SESSION_FS,
        "stateless",
        "cancellable",
    ),
    (
        WriteTool,
        (ResourceClaim(resource="workspace", mode="exclusive"),),
        frozenset({"workspace.write"}),
        "local_mutation",
        False,
        0,
        ToolPlane.SESSION_FS,
        "stateless",
        "cancellable",
    ),
    (
        EditTool,
        (ResourceClaim(resource="workspace", mode="exclusive"),),
        frozenset({"workspace.write"}),
        "local_mutation",
        False,
        0,
        ToolPlane.SESSION_FS,
        "stateless",
        "cancellable",
    ),
    (
        TaskCreateTool,
        (ResourceClaim(resource="task-store", mode="exclusive"),),
        frozenset({"task.write"}),
        "local_mutation",
        False,
        0,
        ToolPlane.CONTROL_PLANE,
        "stateless",
        "cancellable",
    ),
    (
        TaskGetTool,
        (ResourceClaim(resource="task-store", mode="shared_read"),),
        frozenset({"task.read"}),
        "none",
        True,
        0,
        ToolPlane.CONTROL_PLANE,
        "stateless",
        "cancellable",
    ),
    (
        TaskListTool,
        (ResourceClaim(resource="task-store", mode="shared_read"),),
        frozenset({"task.read"}),
        "none",
        True,
        0,
        ToolPlane.CONTROL_PLANE,
        "stateless",
        "cancellable",
    ),
    (
        TaskUpdateTool,
        (ResourceClaim(resource="task-store", mode="exclusive"),),
        frozenset({"task.write"}),
        "local_mutation",
        False,
        0,
        ToolPlane.CONTROL_PLANE,
        "stateless",
        "cancellable",
    ),
    (
        TaskCompleteTool,
        (ResourceClaim(resource="task-store", mode="exclusive"),),
        frozenset({"task.write"}),
        "local_mutation",
        False,
        0,
        ToolPlane.CONTROL_PLANE,
        "stateless",
        "cancellable",
    ),
    (
        WebSearchTool,
        (ResourceClaim(resource="web", mode="counted", max_concurrent=3),),
        frozenset({"web.search"}),
        "external_effect",
        False,
        0,
        ToolPlane.EXTERNAL_SERVICE,
        "stateless",
        "best_effort",
    ),
    (
        WebFetchTool,
        (ResourceClaim(resource="web", mode="counted", max_concurrent=3),),
        frozenset({"web.fetch"}),
        "external_effect",
        False,
        16000,
        ToolPlane.EXTERNAL_SERVICE,
        "stateless",
        "best_effort",
    ),
    (
        SpawnTool,
        (ResourceClaim(resource="spawn", mode="counted", max_concurrent=2),),
        frozenset(),
        "local_mutation",
        False,
        0,
        ToolPlane.CONTROL_PLANE,
        "stateless",
        "non_cancellable",
    ),
    (
        MonitorJobTool,
        (ResourceClaim(resource="workspace+artifact-sync", mode="exclusive"),),
        frozenset({"job.monitor", "artifact.download"}),
        "external_effect",
        False,
        0,
        ToolPlane.EXTERNAL_SERVICE,
        "stateless",
        "best_effort",
    ),
]


@pytest.mark.parametrize(
    (
        "tool_cls",
        "resource_claims",
        "capabilities",
        "effect_level",
        "fast_path_eligible",
        "max_result_chars",
        "plane",
        "state_mode",
        "stop_mode",
    ),
    BUILTIN_EXPECTATIONS,
    ids=[tool_cls.name for tool_cls, *_ in BUILTIN_EXPECTATIONS],
)
def test_builtin_metadata_matches_spec(
    tool_cls,
    resource_claims,
    capabilities,
    effect_level,
    fast_path_eligible,
    max_result_chars,
    plane,
    state_mode,
    stop_mode,
) -> None:
    assert tool_cls.resource_claims == resource_claims
    assert tool_cls.capabilities == capabilities
    assert tool_cls.effect_level == effect_level
    assert tool_cls.fast_path_eligible is fast_path_eligible
    assert tool_cls.max_result_chars == max_result_chars
    assert tool_cls.plane == plane
    assert tool_cls.state_mode == state_mode
    assert tool_cls.stop_mode == stop_mode
    assert tool_cls.exposed_to_model is True
