"""ToolSchemaCache -- load pre-cached MCP tool schemas from local JSON files.

Cache files are generated by `matmaster.tools.cache_mcp_schemas` CLI tool
and stored in matmaster/cache/<server_name>.json. Each file contains the
filtered tool list (post tool_include_only, sync_tools, dedup).
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

logger = logging.getLogger(__name__)

_SCHEMA_CACHE_TOOL_EXCLUDE: dict[str, set[str]] = {
    'mat_sg': {'get_structure_info'},
}


class ToolSchemaCache:
    """Read-only cache of MCP tool schemas. No TTL, no auto-sync."""

    def __init__(self, cache_dir: Path) -> None:
        self.cache_dir = Path(cache_dir)

    def load(self, server_name: str) -> list[dict] | None:
        """Load all tool schemas for a server. Returns None if cache miss."""
        path = self.cache_dir / f"{server_name}.json"
        if not path.exists():
            logger.debug("Cache miss for MCP server '%s' at %s", server_name, path)
            return None
        try:
            schemas = json.loads(path.read_text(encoding='utf-8'))
        except (json.JSONDecodeError, OSError) as e:
            logger.warning("Failed to read cache for '%s': %s", server_name, e)
            return None
        if not isinstance(schemas, list):
            logger.warning("Invalid cache format for '%s': expected list", server_name)
            return None
        excluded = _SCHEMA_CACHE_TOOL_EXCLUDE.get(server_name, set())
        if not excluded:
            return schemas
        return [tool for tool in schemas if tool.get('name') not in excluded]
