"""
Orchestrate a deep literature survey: plan queries, collect metadata, optionally fetch full text,
and append findings to a Markdown report. Paper search is done via MCP tools (repeatedly);
this script can emit a search plan and coordinates file output.

For serious writing, the agent MUST expand the topic into facets and call retrieval tools
repeatedly (see reference/search_facets_and_rounds.md)—at least 6–15 retrieval calls, not 1–2.

Usage:
  python run_survey.py --topic "DPA-2 for Alloys" --depth "deep" --output "survey_dpa.md"
  python run_survey.py --topic "Perovskite stability" --depth "deep" --write_plan

Output: Creates or appends to _tmp/surveys/<output>; optionally writes a search-plan checklist.
"""

import argparse
import re
from pathlib import Path

# Standard facets to expand from topic (see reference/search_facets_and_rounds.md)
DEFAULT_FACETS = [
    "Definition",
    "Mechanism",
    "Methods",
    "Reviews / state of the art",
    "Caveats",
]


def _project_tmp() -> Path:
    cwd = Path.cwd()
    for p in [cwd, cwd.parent, cwd.parent.parent]:
        t = p / "_tmp"
        t.mkdir(parents=True, exist_ok=True)
        return t
    (cwd / "_tmp").mkdir(parents=True, exist_ok=True)
    return cwd / "_tmp"


def sanitize_topic(topic: str) -> str:
    """Sanitize topic for use in filenames."""
    return re.sub(r"[^\w\s-]", "", topic).strip().replace(" ", "_")[:80]


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Run a deep literature survey and write a report to a Markdown file."
    )
    ap.add_argument("--topic", required=True, help="Survey topic (e.g. 'DPA-2 for Alloys')")
    ap.add_argument("--depth", default="deep", choices=["quick", "deep"], help="Survey depth")
    ap.add_argument(
        "--output",
        default=None,
        help="Output filename (default: survey_<sanitized_topic>.md)",
    )
    ap.add_argument(
        "--write_plan",
        action="store_true",
        help="Write a search-plan checklist (facets + example queries) to _tmp/surveys/<topic>_plan.md",
    )
    args = ap.parse_args()

    base = _project_tmp() / "surveys"
    base.mkdir(parents=True, exist_ok=True)
    out_name = args.output or f"survey_{sanitize_topic(args.topic)}.md"
    out_path = base / out_name

    if args.write_plan:
        plan_path = base / f"{sanitize_topic(args.topic)}_plan.md"
        plan_lines = [
            f"# Search plan: {args.topic}",
            "",
            "**Rule**: Repeatedly call retrieval tools (paper + web search) for each facet. Minimum ~6–15 total calls.",
            "",
            "## Facets and example queries (run multiple searches per facet)",
            "",
        ]
        for i, facet in enumerate(DEFAULT_FACETS, 1):
            plan_lines.append(f"### {i}. {facet}")
            plan_lines.append("")
            plan_lines.append("- [ ] Query variant 1 (e.g. topic + facet keyword)")
            plan_lines.append("- [ ] Query variant 2 (synonym or alternate language)")
            plan_lines.append("- [ ] Query variant 3 (e.g. \"X review\" or \"X mechanism\")")
            plan_lines.append("")
        plan_lines.append("## Tools to call repeatedly")
        plan_lines.append("")
        plan_lines.append("- `mat_sn_search-papers-normal`, `mat_sn_scholar-search`, `mat_sn_search-papers-enhanced`")
        plan_lines.append("- `mat_sn_web-search` (definitions, tutorials)")
        plan_lines.append("- After each search: filter relevance, then continue to next query/facet.")
        plan_path.write_text("\n".join(plan_lines), encoding="utf-8")
        print(f"Search plan written to {plan_path}. Run retrieval for each facet before synthesizing.")

    # Placeholder: real implementation would call MCP/search, RAG, then write sections.
    # Here we create the file with a minimal outline so the skill is usable end-to-end.
    outline = f"""# Survey: {args.topic}

*Generated by deep-survey (depth={args.depth}). Replace this with run_survey logic that calls paper search, filters, and appends sections.*

## Executive Summary
(TBD)

## Key Methodologies
(TBD)

## State of the Art
(TBD)

## Gap Analysis
(TBD)

## References
(TBD)
"""
    out_path.write_text(outline, encoding="utf-8")
    print(f"Survey completed. Saved to {out_path}.")


if __name__ == "__main__":
    main()
