"""GROMACS MDP backend for input-manual-helper."""

from __future__ import annotations

from typing import Any

from engine.completion import CompletionItem
from engine.diagnostics import Diagnostic
from engine.document import DocumentModel, ParsedParam, SourceRange
from engine.renderer import RenderIntent
from engine.schema import SchemaRegistry
from engine.software.base import SoftwareBackend


def _make_range(line: int, col_start: int, col_end: int) -> SourceRange:
    return SourceRange(
        start_line=line,
        start_col=col_start,
        end_line=line,
        end_col=col_end,
    )


def _strip_comment(line: str) -> str:
    for marker in (";", "#"):
        idx = line.find(marker)
        if idx >= 0:
            line = line[:idx]
    return line


def _parse_numeric(value: Any) -> float | None:
    try:
        return float(str(value).strip())
    except (TypeError, ValueError):
        return None


class GROMACSBackend(SoftwareBackend):
    """Parse, render, and diagnose GROMACS `.mdp` parameter files."""

    software_name = "gromacs"

    def parse(self, text: str, source: str = "<string>") -> DocumentModel:
        doc = DocumentModel(software=self.software_name, source=source, raw_text=text)
        for lineno, raw_line in enumerate(text.splitlines(), start=1):
            line = _strip_comment(raw_line).strip()
            if not line:
                continue
            if "=" not in line:
                doc.parse_errors.append(
                    Diagnostic(
                        severity="warning",
                        message="MDP line does not contain key = value syntax.",
                        range=_make_range(lineno, 0, len(raw_line)),
                        param="syntax",
                        suggestion="Use `key = value` for GROMACS MDP parameters.",
                        rule_id="gromacs-mdp-syntax",
                    )
                )
                continue
            key, value = line.split("=", 1)
            key = key.strip()
            value = value.strip()
            col_start = raw_line.find(key)
            doc.params.append(
                ParsedParam(
                    name=key,
                    value=value,
                    raw_text=raw_line,
                    range=_make_range(lineno, col_start, len(raw_line)),
                )
            )
        return doc

    def render(self, intent: RenderIntent) -> str:
        task = intent.task_type.lower().replace("-", "_")
        if task not in {"em", "minimize", "minimization", "energy_minimization"}:
            raise ValueError(
                f"Unsupported GROMACS task {intent.task_type!r}; supported: em"
            )

        params = {
            "integrator": "steep",
            "nsteps": "50000",
            "emtol": "1000.0",
            "emstep": "0.01",
            "cutoff-scheme": "Verlet",
            "nstlist": "10",
            "coulombtype": "PME",
            "rcoulomb": "1.0",
            "rvdw": "1.0",
            "pbc": "xyz",
        }
        for key, value in intent.params.items():
            params[str(key)] = str(value)

        lines = [
            "; Generated by input-manual-helper engine (GROMACSBackend)",
            "; Task: energy minimization",
        ]
        lines.extend(f"{key:<24}= {value}" for key, value in params.items())
        return "\n".join(lines) + "\n"

    def get_diagnostics(
        self, doc: DocumentModel, schema: SchemaRegistry
    ) -> list[Diagnostic]:
        diagnostics = list(doc.parse_errors)
        params = {p.name.lower(): p for p in doc.params}

        def require(name: str, message: str) -> None:
            if name not in params:
                diagnostics.append(
                    Diagnostic(
                        severity="error",
                        message=message,
                        param=name,
                        suggestion=f"Add `{name} = ...` to the MDP file.",
                        rule_id=f"gromacs-missing-{name}",
                    )
                )

        require("integrator", "Missing GROMACS integrator.")
        require("nsteps", "Missing number of MD/minimization steps.")

        integrator = str(
            params.get(
                "integrator", ParsedParam("", "", "", _make_range(1, 0, 0))
            ).value
        ).lower()
        if integrator in {"steep", "cg", "l-bfgs", "lbfgs"}:
            require("emtol", "Energy minimization requires emtol.")
            require("emstep", "Energy minimization requires emstep.")

        numeric_rules = {
            "nsteps": (1.0, None, "error"),
            "emtol": (0.0, None, "error"),
            "emstep": (0.0, 0.1, "warning"),
            "rcoulomb": (0.1, 5.0, "warning"),
            "rvdw": (0.1, 5.0, "warning"),
        }
        for name, (low, high, severity) in numeric_rules.items():
            param = params.get(name)
            if param is None:
                continue
            value = _parse_numeric(param.value)
            if value is None:
                diagnostics.append(
                    Diagnostic(
                        severity="error",
                        message=f"{name} must be numeric.",
                        range=param.range,
                        param=name,
                        suggestion=f"Set `{name}` to a numeric value.",
                        rule_id=f"gromacs-{name}-numeric",
                    )
                )
                continue
            if value <= low or (high is not None and value > high):
                diagnostics.append(
                    Diagnostic(
                        severity=severity,
                        message=f"{name}={value:g} is outside the usual range.",
                        range=param.range,
                        param=name,
                        suggestion=(
                            f"Use {name} > {low:g}"
                            if high is None
                            else f"Use {low:g} < {name} <= {high:g}"
                        ),
                        rule_id=f"gromacs-{name}-range",
                    )
                )

        cutoff_scheme = params.get("cutoff-scheme")
        if cutoff_scheme is None:
            diagnostics.append(
                Diagnostic(
                    severity="warning",
                    message="cutoff-scheme is missing.",
                    param="cutoff-scheme",
                    suggestion="Use `cutoff-scheme = Verlet` for modern GROMACS.",
                    rule_id="gromacs-cutoff-scheme-missing",
                )
            )
        elif str(cutoff_scheme.value).strip().lower() != "verlet":
            diagnostics.append(
                Diagnostic(
                    severity="warning",
                    message="Non-Verlet cutoff scheme may be legacy or incompatible.",
                    range=cutoff_scheme.range,
                    param="cutoff-scheme",
                    suggestion="Prefer `cutoff-scheme = Verlet` unless reproducing an old setup.",
                    rule_id="gromacs-cutoff-scheme-legacy",
                )
            )

        return diagnostics

    def get_completions(
        self,
        doc: DocumentModel,
        line: int,
        col: int,
        schema: SchemaRegistry,
    ) -> list[CompletionItem]:
        names = [
            "integrator",
            "nsteps",
            "emtol",
            "emstep",
            "cutoff-scheme",
            "coulombtype",
            "rcoulomb",
            "rvdw",
            "pbc",
        ]
        return [
            CompletionItem(
                label=name,
                insert_text=f"{name} = ",
                kind="parameter",
                detail="GROMACS MDP parameter",
                sort_priority=i,
            )
            for i, name in enumerate(names)
        ]
